const currencies = [
  "AED - United Arab Emirates",
  "AFN - Afghanistan",
  "ALL - Albania",
  "AMD - Armenia",
  "ANG - Curaçao, Sint Maarten",
  "AOA - Angola",
  "ARS - Argentina",
  "AUD - Australia",
  "AWG - Aruba",
  "AZN - Azerbaijan",
  "BAM - Bosnia and Herzegovina",
  "BBD - Barbados",
  "BDT - Bangladesh",
  "BGN - Bulgaria",
  "BHD - Bahrain",
  "BIF - Burundi",
  "BMD - Bermuda",
  "BND - Brunei",
  "BOB - Bolivia",
  "BRL - Brazil",
  "BSD - Bahamas",
  "BTC - Cryptocurrency",
  "BTN - Bhutan",
  "BWP - Botswana",
  "BYN - Belarus",
  "BZD - Belize",
  "CAD - Canada",
  "CDF - Democratic Republic of the Congo",
  "CHF - Switzerland",
  "CLF - Chile",
  "CLP - Chile",
  "CNY - China",
  "COP - Colombia",
  "CRC - Costa Rica",
  "CUC - Cuba",
  "CUP - Cuba",
  "CVE - Cape Verde",
  "CZK - Czech Republic",
  "DJF - Djibouti",
  "DKK - Denmark",
  "DOP - Dominican Republic",
  "DZD - Algeria",
  "EGP - Egypt",
  "ERN - Eritrea",
  "ETB - Ethiopia",
  "EUR - Eurozone",
  "FJD - Fiji",
  "FKP - Falkland Islands",
  "GBP - United Kingdom",
  "GEL - Georgia",
  "GGP - Guernsey",
  "GHS - Ghana",
  "GIP - Gibraltar",
  "GMD - Gambia",
  "GNF - Guinea",
  "GTQ - Guatemala",
  "GYD - Guyana",
  "HKD - Hong Kong",
  "HNL - Honduras",
  "HRK - Croatia",
  "HTG - Haiti",
  "HUF - Hungary",
  "IDR - Indonesia",
  "ILS - Israel",
  "IMP - Isle of Man",
  "INR - India",
  "IQD - Iraq",
  "IRR - Iran",
  "ISK - Iceland",
  "JEP - Jersey",
  "JMD - Jamaica",
  "JOD - Jordan",
  "JPY - Japan",
  "KES - Kenya",
  "KGS - Kyrgyzstan",
  "KHR - Cambodia",
  "KMF - Comoros",
  "KPW - North Korea",
  "KRW - South Korea",
  "KWD - Kuwait",
  "KYD - Cayman Islands",
  "KZT - Kazakhstan",
  "LAK - Laos",
  "LBP - Lebanon",
  "LKR - Sri Lanka",
  "LRD - Liberia",
  "LSL - Lesotho",
  "LYD - Libya",
  "MAD - Morocco",
  "MDL - Moldova",
  "MGA - Madagascar",
  "MKD - North Macedonia",
  "MMK - Myanmar",
  "MNT - Mongolia",
  "MOP - Macau",
  "MRO - Mauritania",
  "MRU - Mauritania",
  "MUR - Mauritius",
  "MVR - Maldives",
  "MWK - Malawi",
  "MXN - Mexico",
  "MYR - Malaysia",
  "MZN - Mozambique",
  "NAD - Namibia",
  "NGN - Nigeria",
  "NIO - Nicaragua",
  "NOK - Norway",
  "NPR - Nepal",
  "NZD - New Zealand",
  "OMR - Oman",
  "PAB - Panama",
  "PEN - Peru",
  "PGK - Papua New Guinea",
  "PHP - Philippines",
  "PKR - Pakistan",
  "PLN - Poland",
  "PYG - Paraguay",
  "QAR - Qatar",
  "RON - Romania",
  "RSD - Serbia",
  "RUB - Russia",
  "RWF - Rwanda",
  "SAR - Saudi Arabia",
  "SBD - Solomon Islands",
  "SCR - Seychelles",
  "SDG - Sudan",
  "SEK - Sweden",
  "SGD - Singapore",
  "SHP - Saint Helena",
  "SLL - Sierra Leone",
  "SOS - Somalia",
  "SRD - Suriname",
  "SSP - South Sudan",
  "STD - São Tomé and Príncipe",
  "STN - São Tomé and Príncipe",
  "SVC - El Salvador",
  "SYP - Syria",
  "SZL - Eswatini",
  "THB - Thailand",
  "TJS - Tajikistan",
  "TMT - Turkmenistan",
  "TND - Tunisia",
  "TOP - Tonga",
  "TRY - Turkey",
  "TTD - Trinidad and Tobago",
  "TWD - Taiwan",
  "TZS - Tanzania",
  "UAH - Ukraine",
  "UGX - Uganda",
  "USD - United States",
  "UYU - Uruguay",
  "UZS - Uzbekistan",
  "VEF - Venezuela",
  "VES - Venezuela",
  "VND - Vietnam",
  "VUV - Vanuatu",
  "WST - Samoa",
  "XAF - Central African CFA Franc",
  "XAG - Silver (troy ounce)",
  "XAU - Gold (troy ounce)",
  "XCD - East Caribbean Dollar",
  "XDR - Special Drawing Rights (IMF)",
  "XOF - West African CFA Franc",
  "XPD - Palladium (troy ounce)",
  "XPF - CFP Franc",
  "XPT - Platinum (troy ounce)",
  "YER - Yemen",
  "ZAR - South Africa",
  "ZMW - Zambia",
  "ZWL - Zimbabwe"
];
